<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UniversalVariability" nsURI="https://transformationtoolcontest.github.io/uvl"
    nsPrefix="uvl">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//FeatureGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGroup" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrFeatureGroup" eSuperTypes="#//FeatureGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryFeatureGroup" eSuperTypes="#//FeatureGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalFeatureGroup" eSuperTypes="#//FeatureGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeFeatureGroup" eSuperTypes="#//FeatureGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImpliesConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="given" lowerBound="1" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consequence" lowerBound="1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalenceConstraint" eSuperTypes="#//BinaryConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryConstraint" abstract="true" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndConstraint" eSuperTypes="#//BinaryConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrConstraint" eSuperTypes="#//BinaryConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inner" lowerBound="1" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
